apiVersion: apps/v1
kind: Deployment
metadata:
  name: weirdjs
  labels:
    category: misc
    challenge: weirdjs
spec:
  replicas: 2
  selector:
    matchLabels:
      category: misc
      challenge: weirdjs
  template:
    metadata:
      labels:
        category: misc
        challenge: weirdjs
    spec:
      enableServiceLinks: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/weirdjs
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30