apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    category: web
    challenge: ctfdb
  name: mysql
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
