apiVersion: apps/v1
kind: Deployment
metadata:
  name: infinity-castle
  labels:
    category: linux
    challenge: infinity-castle
spec:
  replicas: 2
  selector:
    matchLabels:
      category: linux
      challenge: infinity-castle
  template:
    metadata:
      labels:
        category: linux
        challenge: infinity-castle
    spec:
      enableServiceLinks: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/infinity-castle
        resources:
          limits:
            cpu: 100m
            memory: 150Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30
