apiVersion: apps/v1
kind: Deployment
metadata:
  name: bash
  labels:
    category: linux
    challenge: bash
spec:
  replicas: 2
  selector:
    matchLabels:
      category: linux
      challenge: bash
  template:
    metadata:
      labels:
        category: linux
        challenge: bash
    spec:
      enableServiceLinks: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/bash
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
        livenessProbe:
          tcpSocket:
            port: tcp
          initialDelaySeconds: 3
          periodSeconds: 30