apiVersion: apps/v1
kind: Deployment
metadata:
  name: lucky-number
  labels:
    category: pwn
    challenge: lucky-number
spec:
  replicas: 2
  selector:
    matchLabels:
      category: pwn
      challenge: lucky-number
  template:
    metadata:
      labels:
        category: pwn
        challenge: lucky-number
    spec:
      enableServiceLinks: false
      containers:
      - name: server
        image: gcr.io/glowing-reserve-336013/lucky-number
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 1337
          name: tcp
