apiVersion: apps/v1
kind: Deployment
metadata:
  name: colourflage
  labels:
    category: forensics
    challenge: colourflage
spec:
  replicas: 2
  selector:
    matchLabels:
      category: forensics
      challenge: colourflage
  template:
    metadata:
      labels:
        category: forensics
        challenge: colourflage
    spec:
      enableServiceLinks: false
      containers:
      - name: web
        image: gcr.io/glowing-reserve-336013/colourflage
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 30Mi
        ports:
        - containerPort: 80
          name: http
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 30