version: "3"

services:
  app:
    build:
      context: challenge
      dockerfile: app.Dockerfile
    image: gcr.io/glowing-reserve-336013/ctfdb_app
    ports:
      - "3004:4444"
    depends_on:
      - db
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

  db:
    build:
      context: challenge
      dockerfile: db.Dockerfile
    image: gcr.io/glowing-reserve-336013/ctfdb_db
    environment:
      - MYSQL_ROOT_PASSWORD=53654db66d94b4154783c1ee0b536920
      - MYSQL_DATABASE=ctfdb
    volumes:
      - .data/mysql:/var/lib/mysql
    restart: always
